---
- name: Configure router interfaces
  hosts: cisco_router
  gather_facts: no  # Not required for basic config tasks
  tasks:
    - name: Set a loopback address for Cisco
      cisco.ios.ios_config:
        lines:
          - ip address 10.1.1.1 255.255.255.255
          - no shut
        parents: interface Loopback0
      when: router_os == "Cisco"
      register: result
      
  hosts: juniper_router
  gather_facts: no
  tasks:
    - name: Set a loopback address for Junos
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces lo0.0 family inet address 10.2.2.2/32
          - commit
      when: router_os == "Juniper"
      register: result
  
